### ISSUE TITLE
The _daemon_stdout_opt function adds invalid options

### ISSUE THREAD

**Issue by myback** [samba-in-kubernetes/sambacc#107]
Tools `smbd` and `winbindd`  does not have options `--log-stdout` or `--stdout`
```shell
~ smbd --log-stdout
Invalid option --log-stdout: unknown option

~ winbindd --log-stdout
Invalid option --log-stdout: unknown option
```

```py
def _daemon_stdout_opt(daemon: str) -> str:
    if daemon == "smbd":
        opt = "--log-stdout"
    else:
        opt = "--stdout"
    opt_lst = get_samba_specifics()
    if _DAEMON_CLI_STDOUT_OPT in opt_lst:
        opt = "--debug-stdout"
    return opt
```

**Comment by phlogistonjohn** [comment]
@anoopcs9 do you know if upstream changed things here (again)?

**Comment by anoopcs9** [comment]
> @anoopcs9 do you know if upstream samba changed things here (again)?

I am not aware of any further changes. Moreover our CI runs should have failed otherwise.

> Tools `smbd` and `winbindd` does not have options `--log-stdout` or `--stdout`
> 
> ```shell
> ~ smbd --log-stdout
> Invalid option --log-stdout: unknown option
> 
> ~ winbindd --log-stdout
> Invalid option --log-stdout: unknown option
> ```

Correct. They were all changed to use `--debug-stdout` instead with [v4.15](https://www.samba.org/samba/history/samba-4.15.0.html).

> ```python
> def _daemon_stdout_opt(daemon: str) -> str:
>     if daemon == "smbd":
>         opt = "--log-stdout"
>     else:
>         opt = "--stdout"
>     opt_lst = get_samba_specifics()
>     if _DAEMON_CLI_STDOUT_OPT in opt_lst:
>         opt = "--debug-stdout"
>     return opt
> ```

@myback Did you miss to notice the call to _get_samba_specifics()_ which should pick "daemon_cli_debug_output"  from the list of comma(`,`) separated values for `SAMBA_SPECIFICS`?

**Comment by anoopcs9** [comment]
I hope things are sorted out for you.

Feel free to reopen if otherwise.
