### ISSUE TITLE
CI Jobs are failing 

### ISSUE THREAD

**Issue by phlogistonjohn** [samba-in-kubernetes/sambacc#113]
The ci jobs have been failing consistently for around a week.

Issue seems to be related to xml libs on f38.

https://github.com/samba-in-kubernetes/sambacc/actions/runs/8677896977

**Comment by anoopcs9** [comment]
I looked into the details and issue seems to be because of old **_expat_** library.

```
ImportError: /usr/lib64/python3.9/lib-dynload/pyexpat.cpython-39-x86_64-linux-gnu.so: undefined symbol: XML_SetReparseDeferralEnabled
```

`XML_SetReparseDeferralEnabled` is only [present](https://github.com/libexpat/libexpat/commit/1d3162da8a85a398ab451aadd6c2ad19587e5a68) from expat v2.6.0 but base image comes with v2.5.0.

This whole issue came up when Python was updated to 3.9.19 where CPython started [exposing](https://github.com/python/cpython/commit/200762426b4b9878c33cdef620aa1a51631dd5df) the said function.

We do have expat v2.6.0 from updates and that might be our way forward.

**Comment by anoopcs9** [comment]
> We do have expat v2.6.0 from updates and that might be our way forward.

CentOS Stream 9 lacks expat updates where it is stuck at v2.5.0 😞.

**Comment by phlogistonjohn** [comment]
I went to implement the CI tweak to let the other jobs proceed with #114 but f38 passed!
I will wait until the next regular CI run but maybe fedora has already resolved the problem, and I can just close this issue.

**Comment by phlogistonjohn** [comment]
Closing. Issue appears to be resolved in distro image

**Comment by anoopcs9** [comment]
> I went to implement the CI tweak to let the other jobs proceed with #114 but f38 passed! I will wait until the next regular CI run but maybe fedora has already resolved the problem, and I can just close this issue.

That pure timing. Fedora [updated](https://bodhi.fedoraproject.org/updates/FEDORA-2024-79b1859d7c) python-3.9.19 to require expat >=2.6.0. Whereas on CentOS Stream 9 we are just a minor release behind(v3.9.18) which prevents us from the expected failure.
