### ISSUE TITLE
Configuring globals does not appear to work

### ISSUE THREAD

**Issue by tunaranch** [samba-in-kubernetes/sambacc#43]
### Discussed in https://github.com/samba-in-kubernetes/sambacc/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **tunaranch** May 30, 2022</sup>
Hi everyone.

I'm trying to stand up a samba AD DC in minikube for testing, and I can't seem to modify smb.conf to disable the strong auth requirement.

Here's my Kubernetes resources, startup log, and generated smb.conf file

https://gist.github.com/09aed2659f5eeeaa176edd5f4d87e801

Have I made a mistake somewhere?</div>

**Comment by tunaranch** [comment]
The problem affects both the ad and regular images, as described in https://github.com/samba-in-kubernetes/sambacc/discussions/42#discussioncomment-2860271

**Comment by phlogistonjohn** [comment]
Looking at the code I am pretty confident that the bug lies in sambacc's addc layer. Global options that are not directly part of the parameters needed for provisioning are silently discarded.  This is misleading as nothing in the docs or structure of the config file indicates that this might be the case.

In the  AD DC path we can't directly write to smb.conf or use the registry backend, but we can pass `--option` parameters to the  `samba-tool domain provision` command.

I don't think the issue affects (file) server images. On the file server images we use the registry backend for samba. This means that only a minimal set of params will exist in smb.conf. To see what parameters have been set up for samba try the commands `net conf list` or `testparm`.

**Comment by fsdrw08** [comment]
any update to this issue?

**Comment by phlogistonjohn** [comment]
Hi @fsdrw08, I'm sorry to say I had started working on this and ran into to some issues between how I assumed samba-tool was going to work versus how it worked in practice, so the effort was more than I anticipated. It's helpful to know someone else is interested in this - perhaps I'll take another look at it soon.
